[build]
  base = "."
  publish = "dist"  # Changez de "client/dist" à simplement "dist" si c'est le chemin correct
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
